Added note about possible error message, which is indication of API connection error
TypeError: getresponse() got an unexpected keyword argument 'buffering'